(() => {
  'use strict';
  const isEs=()=>((localStorage.getItem('droop-language')||localStorage.getItem('droop-lang')||navigator.language||'en').toLowerCase().startsWith('es'));
  const tr=(en,es)=>isEs()?es:en;
  const packs={music:{name:'Music Release',nameEs:'Lanzamiento musical',outputs:[{name:'Square Cover',nameEs:'Portada cuadrada',file:'square-cover-3000x3000.jpg',width:3000,height:3000},{name:'Social Post',nameEs:'Post para redes',file:'social-post-1080x1080.jpg',width:1080,height:1080},{name:'Story / Reel',nameEs:'Historia / Reel',file:'story-1080x1920.jpg',width:1080,height:1920},{name:'YouTube Thumbnail',nameEs:'Miniatura de YouTube',file:'youtube-thumbnail-1280x720.jpg',width:1280,height:720}]},youtube:{name:'YouTube Launch',nameEs:'Lanzamiento en YouTube',outputs:[{name:'Thumbnail',nameEs:'Miniatura',file:'youtube-thumbnail-1280x720.jpg',width:1280,height:720},{name:'Square Promo',nameEs:'Promo cuadrada',file:'square-promo-1080x1080.jpg',width:1080,height:1080},{name:'Story / Short',nameEs:'Historia / Short',file:'vertical-promo-1080x1920.jpg',width:1080,height:1920}]},social:{name:'Social Pack',nameEs:'Pack para redes',outputs:[{name:'Square Post',nameEs:'Post cuadrado',file:'square-post-1080x1080.jpg',width:1080,height:1080},{name:'Portrait Post',nameEs:'Post vertical',file:'portrait-post-1080x1350.jpg',width:1080,height:1350},{name:'Story / Reel',nameEs:'Historia / Reel',file:'story-1080x1920.jpg',width:1080,height:1920}]},profile:{name:'Profile Pack',nameEs:'Pack de perfil',outputs:[{name:'Large Avatar',nameEs:'Avatar grande',file:'avatar-1024x1024.jpg',width:1024,height:1024},{name:'Medium Avatar',nameEs:'Avatar mediano',file:'avatar-512x512.jpg',width:512,height:512},{name:'Small Avatar',nameEs:'Avatar chico',file:'avatar-256x256.jpg',width:256,height:256}]}};
  const input=document.getElementById('packFileInput'),drop=document.getElementById('packDropZone'),info=document.getElementById('packFileInfo'),select=document.getElementById('packSelect'),generate=document.getElementById('packGenerateButton'),result=document.getElementById('packResult'),grid=document.getElementById('packResultGrid'),downloadAll=document.getElementById('packDownloadAll');
  const idleGenerate=generate.textContent;
  let file=null,generated=[];
  function setFile(next){if(!next)return;if(!next.type.startsWith('image/')){input.value='';return alert(tr('Please choose an image file.','Elegí un archivo de imagen.'));}file=next;info.hidden=false;info.textContent=`${next.name} · ${(next.size/1024/1024).toFixed(2)} MB`;generate.disabled=false;result.hidden=true;clearGenerated();}
  function clearGenerated(){generated.forEach(x=>URL.revokeObjectURL(x.url));generated=[];grid.innerHTML='';}
  function loadImage(source){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(source),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('decode'))};img.src=url;});}
  function renderBlob(img,o){return new Promise(resolve=>{const c=document.createElement('canvas');c.width=o.width;c.height=o.height;const ctx=c.getContext('2d'),sr=img.naturalWidth/img.naturalHeight,tr=o.width/o.height;let sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight;if(sr>tr){sw=img.naturalHeight*tr;sx=(img.naturalWidth-sw)/2}else{sh=img.naturalWidth/tr;sy=(img.naturalHeight-sh)/2}ctx.fillStyle='#fff';ctx.fillRect(0,0,o.width,o.height);ctx.drawImage(img,sx,sy,sw,sh,0,0,o.width,o.height);c.toBlob(resolve,'image/jpeg',.92);});}
  function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  function crc32(bytes){let c=-1;for(let i=0;i<bytes.length;i++){c^=bytes[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xEDB88320:0)}return(c^(-1))>>>0}
  function u16(v){const a=new Uint8Array(2);new DataView(a.buffer).setUint16(0,v,true);return a}
  function u32(v){const a=new Uint8Array(4);new DataView(a.buffer).setUint32(0,v>>>0,true);return a}
  function concat(parts){const len=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(len);let off=0;for(const p of parts){out.set(p,off);off+=p.length}return out}
  async function buildZip(items){const enc=new TextEncoder(),locals=[],centrals=[];let offset=0;for(const item of items){const name=enc.encode(item.name),data=new Uint8Array(await item.blob.arrayBuffer()),crc=crc32(data),size=data.length;const local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(size),u32(size),u16(name.length),u16(0),name,data]);locals.push(local);const central=concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(size),u32(size),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);centrals.push(central);offset+=local.length}const centralSize=centrals.reduce((n,p)=>n+p.length,0),centralOffset=offset,eocd=concat([u32(0x06054b50),u16(0),u16(0),u16(items.length),u16(items.length),u32(centralSize),u32(centralOffset),u16(0)]);return new Blob([...locals,...centrals,eocd],{type:'application/zip'})}
  input.addEventListener('click',()=>{input.value='';});input.addEventListener('change',e=>setFile(e.target.files[0]));['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));select.addEventListener('change',()=>{result.hidden=true;clearGenerated()});
  generate.addEventListener('click',async()=>{if(!file)return;generate.disabled=true;generate.textContent=tr('Generating pack…','Generando pack…');clearGenerated();try{const img=await loadImage(file),pack=packs[select.value];for(const o of pack.outputs){const blob=await renderBlob(img,o);if(!blob)continue;const url=URL.createObjectURL(blob),displayName=isEs()?o.nameEs:o.name;generated.push({...o,blob,url});const card=document.createElement('article');card.className='pack-output-card';card.innerHTML=`<img src="${url}" alt="${displayName} preview"><div><strong>${displayName}</strong><span>${o.width} × ${o.height} · ${(blob.size/1024).toFixed(0)} KB</span></div><button type="button">${tr('Download','Descargar')}</button>`;card.querySelector('button').addEventListener('click',()=>downloadBlob(blob,o.file));grid.appendChild(card)}document.getElementById('packResultTitle').textContent=tr(`${pack.name} · ${generated.length} files ready`,`${pack.nameEs} · ${generated.length} archivos listos`);result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'nearest'});}catch(_){alert(tr('Could not read this image. Try JPG, PNG or WebP.','No se pudo leer esta imagen. Probá con JPG, PNG o WebP.'))}finally{generate.disabled=false;generate.textContent=idleGenerate}});
  downloadAll.addEventListener('click',async()=>{if(!generated.length)return;const old=downloadAll.textContent;downloadAll.disabled=true;downloadAll.textContent=tr('Building ZIP…','Armando ZIP…');try{const items=generated.map(x=>({name:x.file,blob:x.blob})),zip=await buildZip(items);downloadBlob(zip,`droop-${select.value}-pack.zip`)}catch(e){console.error(e);alert(tr('Could not build the ZIP. You can still download each file individually.','No se pudo crear el ZIP. Igual podés descargar cada archivo por separado.'))}finally{downloadAll.disabled=false;downloadAll.textContent=old}});
})();