(() => {
  'use strict';
  const packs={music:{name:'Music Release',outputs:[{name:'Square Cover',file:'square-cover-3000x3000.jpg',width:3000,height:3000},{name:'Social Post',file:'social-post-1080x1080.jpg',width:1080,height:1080},{name:'Story / Reel',file:'story-1080x1920.jpg',width:1080,height:1920},{name:'YouTube Thumbnail',file:'youtube-thumbnail-1280x720.jpg',width:1280,height:720}]},youtube:{name:'YouTube Launch',outputs:[{name:'Thumbnail',file:'youtube-thumbnail-1280x720.jpg',width:1280,height:720},{name:'Square Promo',file:'square-promo-1080x1080.jpg',width:1080,height:1080},{name:'Story / Short',file:'vertical-promo-1080x1920.jpg',width:1080,height:1920}]},social:{name:'Social Pack',outputs:[{name:'Square Post',file:'square-post-1080x1080.jpg',width:1080,height:1080},{name:'Portrait Post',file:'portrait-post-1080x1350.jpg',width:1080,height:1350},{name:'Story / Reel',file:'story-1080x1920.jpg',width:1080,height:1920}]},profile:{name:'Profile Pack',outputs:[{name:'Large Avatar',file:'avatar-1024x1024.jpg',width:1024,height:1024},{name:'Medium Avatar',file:'avatar-512x512.jpg',width:512,height:512},{name:'Small Avatar',file:'avatar-256x256.jpg',width:256,height:256}]}};
  const input=document.getElementById('packFileInput'),drop=document.getElementById('packDropZone'),info=document.getElementById('packFileInfo'),select=document.getElementById('packSelect'),generate=document.getElementById('packGenerateButton'),result=document.getElementById('packResult'),grid=document.getElementById('packResultGrid'),downloadAll=document.getElementById('packDownloadAll');
  let file=null,generated=[];
  function setFile(next){if(!next||!next.type.startsWith('image/'))return alert('Please choose an image file.');file=next;info.hidden=false;info.textContent=`${next.name} · ${(next.size/1024/1024).toFixed(2)} MB`;generate.disabled=false;result.hidden=true;clearGenerated();}
  function clearGenerated(){generated.forEach(x=>URL.revokeObjectURL(x.url));generated=[];grid.innerHTML='';}
  function loadImage(source){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(source),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('decode'))};img.src=url;});}
  function renderBlob(img,o){return new Promise(resolve=>{const c=document.createElement('canvas');c.width=o.width;c.height=o.height;const ctx=c.getContext('2d'),sr=img.naturalWidth/img.naturalHeight,tr=o.width/o.height;let sx=0,sy=0,sw=img.naturalWidth,sh=img.naturalHeight;if(sr>tr){sw=img.naturalHeight*tr;sx=(img.naturalWidth-sw)/2}else{sh=img.naturalWidth/tr;sy=(img.naturalHeight-sh)/2}ctx.fillStyle='#fff';ctx.fillRect(0,0,o.width,o.height);ctx.drawImage(img,sx,sy,sw,sh,0,0,o.width,o.height);c.toBlob(resolve,'image/jpeg',.92);});}
  function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
  input.addEventListener('change',e=>setFile(e.target.files[0]));['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));select.addEventListener('change',()=>{result.hidden=true;clearGenerated()});
  generate.addEventListener('click',async()=>{if(!file)return;generate.disabled=true;generate.textContent='Generating pack…';clearGenerated();try{const img=await loadImage(file),pack=packs[select.value];for(const o of pack.outputs){const blob=await renderBlob(img,o);if(!blob)continue;const url=URL.createObjectURL(blob);generated.push({...o,blob,url});const card=document.createElement('article');card.className='pack-output-card';card.innerHTML=`<img src="${url}" alt="${o.name} preview"><div><strong>${o.name}</strong><span>${o.width} × ${o.height} · ${(blob.size/1024).toFixed(0)} KB</span></div><button type="button">Download</button>`;card.querySelector('button').addEventListener('click',()=>downloadBlob(blob,o.file));grid.appendChild(card)}document.getElementById('packResultTitle').textContent=`${pack.name} · ${generated.length} files ready`;result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'nearest'});}catch(_){alert('Could not read this image. Try JPG, PNG or WebP.')}finally{generate.disabled=false;generate.textContent='Generate pack'}});
  downloadAll.addEventListener('click',async()=>{if(!generated.length)return;if(typeof JSZip==='undefined'){alert('ZIP engine did not load. Refresh the page and try again.');return}const old=downloadAll.textContent;downloadAll.disabled=true;downloadAll.textContent='Building ZIP…';try{const zip=new JSZip(),pack=packs[select.value];generated.forEach(item=>zip.file(item.file,item.blob));zip.file('README.txt',`CreatorTools — ${pack.name}\n${generated.length} files generated locally in your browser.\n`);const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE',compressionOptions:{level:6}});downloadBlob(blob,`creatortools-${select.value}-pack.zip`);}catch(_){alert('Could not build the ZIP. You can still download each file individually.')}finally{downloadAll.disabled=false;downloadAll.textContent=old}});
})();