(() => {
  'use strict';
  const isEs=()=>((localStorage.getItem('droop-language')||localStorage.getItem('droop-lang')||navigator.language||'en').toLowerCase().startsWith('es'));
  const tr=(en,es)=>isEs()?es:en;
  const presets={tiktok:{name:'TikTok',width:1080,height:1920,zones:[{cls:'safe-top',label:'KEEP CLEAR',labelEs:'DEJAR LIBRE'},{cls:'safe-right',label:'UI',labelEs:'INTERFAZ'},{cls:'safe-bottom',label:'CAPTION / NAV',labelEs:'TEXTO / NAV'}]},reels:{name:'Instagram Reels',width:1080,height:1920,zones:[{cls:'safe-top',label:'KEEP CLEAR',labelEs:'DEJAR LIBRE'},{cls:'safe-right',label:'UI',labelEs:'INTERFAZ'},{cls:'safe-bottom',label:'CAPTION / NAV',labelEs:'TEXTO / NAV'}]},shorts:{name:'YouTube Shorts',width:1080,height:1920,zones:[{cls:'safe-top',label:'KEEP CLEAR',labelEs:'DEJAR LIBRE'},{cls:'safe-right',label:'UI',labelEs:'INTERFAZ'},{cls:'safe-bottom',label:'TITLE / NAV',labelEs:'TÍTULO / NAV'}]}};
  const input=document.getElementById('safeFileInput'),drop=document.getElementById('safeDropZone'),info=document.getElementById('safeFileInfo'),select=document.getElementById('safePreset'),stage=document.getElementById('safeStage'),img=document.getElementById('safePreview'),overlay=document.getElementById('safeOverlay'),status=document.getElementById('safeStatus');
  let url=null;
  function renderOverlay(){const p=presets[select.value];overlay.innerHTML=`<div class="safe-boundary"><span>${tr('SAFE CONTENT AREA','ÁREA SEGURA')}</span></div>${p.zones.map(z=>`<div class="unsafe-zone ${z.cls}"><span>${isEs()?z.labelEs:z.label}</span></div>`).join('')}`;status.textContent=`${p.name} · ${p.width} × ${p.height} ${tr('preview','vista previa')}`;}
  function setFile(file){if(!file)return;if(!file.type.startsWith('image/')){input.value='';return alert(tr('Please choose an image file.','Elegí un archivo de imagen.'));}if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);stage.hidden=true;img.onload=()=>{stage.hidden=false;info.hidden=false;info.textContent=`${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;renderOverlay();};img.onerror=()=>{stage.hidden=true;alert(tr('Could not read this image.','No se pudo leer esta imagen.'));};img.src=url;}
  input.addEventListener('click',()=>{input.value='';});input.addEventListener('change',e=>setFile(e.target.files[0]));select.addEventListener('change',renderOverlay);['dragenter','dragover'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.add('dragging')}));['dragleave','drop'].forEach(t=>drop.addEventListener(t,e=>{e.preventDefault();drop.classList.remove('dragging')}));drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));renderOverlay();
})();