(()=>{
'use strict';const $=id=>document.getElementById(id),video=$('subVideo');
const copy={
en:{all:'All tools',trim:'Trim video',privacy:'Local processing · No uploads',name:'Subtitle Burner',kicker:'VIDEO · NEW',headline:'Your words. Part of the video.',lead:'Add an SRT file or write your captions with their times. Export a video with subtitles everyone can see.',local:'✦ Made on your device',permanent:'Permanent subtitles',drop:'Drop a video here',choose:'or tap to choose a file',limits:'Up to 2 minutes · 100 MB',previewHelp:'Preview the timing here. Text wrapping may vary slightly in the export.',import:'Import SRT',add:'Add a caption',style:'Style',outline:'White with outline',yellow:'Yellow with outline',box:'White on black',position:'Position',bottom:'Bottom',top:'Top',size:'Text size',small:'Small',medium:'Medium',large:'Large',export:'Create subtitled video',output:'MP4 · Original audio kept · Lightweight export',cancel:'Cancel',download:'Download subtitled video',info1h:'Bring your captions',info1p:'Import a UTF-8 SRT file or add each phrase with its start and end time. You can edit every caption before exporting.',info2h:'Make them readable',info2p:'Choose a color, outline or background and position your captions near the top or bottom. Imported formatting is replaced by your chosen style.',info3h:'Always visible',info3p:'Subtitles become part of the picture and cannot be switched off. Keep the original video. This version exports up to 1280 pixels on the longest side.',footer:'droop · Everything you need before you post.',start:'Start (seconds)',end:'End (seconds)',text:'Caption',remove:'Remove caption',count:'captions',empty:'Add text to every caption before exporting.',limit:'Use up to 200 captions, 500 characters each, and an SRT smaller than 100 KB.',format:'Could not read this SRT. Check its timecodes and save it as UTF-8.',range:'Each caption needs an end after its start, within the video duration.',overlap:'Some captions overlap. Adjust their start and end times.',invalid:'Choose a video up to 2 minutes and 100 MB.',unreadable:'Could not open this video. Try an MP4 your browser can play.',preparing:'Preparing…',processing:'Adding your subtitles…',ready:'Ready ✓',failed:'Could not finish this video. Try a shorter or smaller file.',canceled:'Canceled. You can try again.',imported:'Captions imported. Review their times and text.',pageTitle:'Subtitle Burner — droop'},
es:{all:'Todas las herramientas',trim:'Recortar video',privacy:'Procesamiento local · Sin subidas',name:'Agregar subtítulos',kicker:'VIDEO · NUEVO',headline:'Tus palabras. Parte del video.',lead:'Cargá un SRT o escribí tus frases con sus tiempos. Exportá un video con subtítulos que todos puedan ver.',local:'✦ Hecho en tu dispositivo',permanent:'Subtítulos permanentes',drop:'Soltá un video acá',choose:'o tocá para elegir un archivo',limits:'Hasta 2 minutos · 100 MB',previewHelp:'Revisá los tiempos acá. Los saltos de línea pueden variar un poco al exportar.',import:'Importar SRT',add:'Agregar una frase',style:'Estilo',outline:'Blanco con contorno',yellow:'Amarillo con contorno',box:'Blanco sobre negro',position:'Posición',bottom:'Abajo',top:'Arriba',size:'Tamaño del texto',small:'Pequeño',medium:'Mediano',large:'Grande',export:'Crear video subtitulado',output:'MP4 · Conserva el audio · Exportación liviana',cancel:'Cancelar',download:'Descargar video subtitulado',info1h:'Traé tus subtítulos',info1p:'Importá un SRT en UTF-8 o agregá cada frase con su inicio y fin. Podés corregir todos los subtítulos antes de exportar.',info2h:'Que se puedan leer',info2p:'Elegí color, contorno o fondo y ubicá las frases arriba o abajo. El formato del SRT se reemplaza por el estilo que elijas.',info3h:'Siempre visibles',info3p:'Los subtítulos quedan dentro de la imagen y no se pueden desactivar. Conservá el video original. Esta versión exporta hasta 1280 píxeles en el lado mayor.',footer:'droop · Todo lo que necesitás antes de publicar.',start:'Inicio (segundos)',end:'Fin (segundos)',text:'Frase',remove:'Eliminar frase',count:'frases',empty:'Agregá texto a todas las frases antes de exportar.',limit:'Usá hasta 200 frases de 500 caracteres y un SRT de menos de 100 KB.',format:'No se pudo leer el SRT. Revisá los tiempos y guardalo en UTF-8.',range:'Cada frase debe terminar después de su inicio, dentro de la duración del video.',overlap:'Hay frases con tiempos superpuestos. Ajustá sus inicios y finales.',invalid:'Elegí un video de hasta 2 minutos y 100 MB.',unreadable:'No se pudo abrir este video. Probá con un MP4 que tu navegador pueda reproducir.',preparing:'Preparando…',processing:'Agregando tus subtítulos…',ready:'Listo ✓',failed:'No se pudo terminar este video. Probá con un archivo más corto o liviano.',canceled:'Cancelado. Podés volver a intentarlo.',imported:'Subtítulos importados. Revisá sus tiempos y textos.',pageTitle:'Agregar subtítulos al video — droop'}};
let lang=(navigator.language||'en').startsWith('es')?'es':'en';try{const v=localStorage.getItem('droop-language');if(copy[v])lang=v;}catch(_){}
let cues=[],file=null,inputURL=null,outputURL=null,duration=0,active=null,key='',generation=0,importing=false;
const t=k=>copy[lang][k],bytes=n=>`${(n/1048576).toFixed(2)} MB`;
function status(k){key=k;$('subStatus').hidden=!k;$('subStatus').textContent=k?t(k):'';}
function clear(){if(outputURL)URL.revokeObjectURL(outputURL);outputURL=null;$('subOutput').pause();$('subOutput').removeAttribute('src');$('subOutput').load();$('subDownload').removeAttribute('href');$('subResult').hidden=true;}
function controls(){const busy=!!active||importing;$('subControls').disabled=busy;$('subVideoInput').disabled=!!active;$('subExport').disabled=busy||!file||!duration||!cues.length;$('subCancel').hidden=!active;video.controls=!active;$('subDrop').setAttribute('aria-disabled',String(!!active));}
function changed(){clear();status('');preview();controls();}
function preview(){
 const el=$('subCaption'),style=$('subStyle').value,top=$('subPosition').value==='top';
 el.textContent=cues.filter(c=>video.currentTime>=c.start&&video.currentTime<c.end).map(c=>c.text).join('\n');
 el.hidden=!el.textContent;el.style.top=top?'8%':'auto';el.style.bottom=top?'auto':'8%';el.style.color=style==='yellow'?'#ffff00':'#ffffff';el.style.background=style==='box'?'#000000':'transparent';
 if(video.videoWidth){const d=SubtitleFormat.size(video.videoWidth,video.videoHeight);el.style.fontSize=`${SubtitleFormat.fontSize(d.w,d.h,$('subSize').value)*$('subStage').clientWidth/d.w}px`;}
}
function rows(){
 const container=$('subCues');container.replaceChildren();$('subCount').textContent=`${cues.length} / 200 ${t('count')}`;
 cues.forEach((cue,index)=>{
  const row=document.createElement('div');row.className='sub-cue';
  for(const name of ['start','end','text']){
   const label=document.createElement('label');label.textContent=`${t(name)} ${index+1}`;if(name==='text')label.className='sub-text';
   const input=document.createElement(name==='text'?'textarea':'input');if(name!=='text'){input.type='number';input.min='0';input.max=String(duration);input.step='.01';}else{input.maxLength=500;input.rows=2;}
   input.value=cue[name];input.oninput=()=>{cue[name]=name==='text'?input.value:input.valueAsNumber;changed();};label.append(input);row.append(label);
  }
  const remove=document.createElement('button');remove.type='button';remove.className='sub-remove';remove.textContent='×';remove.setAttribute('aria-label',`${t('remove')} ${index+1}`);remove.onclick=()=>{cues.splice(index,1);rows();changed();};row.insertBefore(remove,row.lastChild);container.append(row);
 });controls();
}
function language(){document.documentElement.lang=lang;document.title=t('pageTitle');document.querySelectorAll('[data-copy]').forEach(el=>el.textContent=t(el.dataset.copy));$('subLang').textContent=lang==='es'?'EN':'ES';$('subLang').setAttribute('aria-label',lang==='es'?'Switch to English':'Cambiar a español');rows();preview();status(key);}
$('subLang').onclick=()=>{lang=lang==='es'?'en':'es';try{localStorage.setItem('droop-language',lang);}catch(_){}language();};
function open(f){
 if(!f||active)return;if(f.size>100000000||!(f.type.startsWith('video/')||/\.(mp4|mov|m4v|webm)$/i.test(f.name))){status('invalid');return;}
 const ticket=++generation;video.pause();duration=0;file=f;cues=[];importing=false;clear();rows();controls();$('subEditor').hidden=true;status('preparing');if(inputURL)URL.revokeObjectURL(inputURL);inputURL=URL.createObjectURL(f);
 video.onloadedmetadata=()=>{if(ticket!==generation)return;duration=video.duration;if(!Number.isFinite(duration)||duration<=0||duration>120||!video.videoWidth||!video.videoHeight){duration=0;file=null;status('invalid');controls();return;}$('subFile').textContent=`${f.name} · ${bytes(f.size)}`;$('subFile').hidden=false;$('subEditor').hidden=false;$('subStage').style.width=`min(100%,${380*video.videoWidth/video.videoHeight}px)`;status('');controls();};
 video.onerror=()=>{if(ticket!==generation)return;file=null;duration=0;$('subEditor').hidden=true;status('unreadable');controls();};video.src=inputURL;
}
$('subVideoInput').onclick=()=>{$('subVideoInput').value='';};$('subVideoInput').onchange=e=>open(e.target.files[0]);
['dragenter','dragover'].forEach(k=>$('subDrop').addEventListener(k,e=>e.preventDefault()));$('subDrop').addEventListener('drop',e=>{e.preventDefault();open(e.dataTransfer.files[0]);});
$('subAdd').onclick=()=>{if(cues.length>=200){status('limit');return;}const last=cues.length?Math.max(...cues.map(c=>Number.isFinite(c.end)?c.end:0)):0;const start=Math.min(Math.max(video.currentTime,last),Math.max(0,duration-.1));cues.push({start:+start.toFixed(2),end:+Math.min(duration,start+2).toFixed(2),text:''});rows();changed();};
$('subSrtInput').onclick=()=>{$('subSrtInput').value='';};$('subSrtInput').onchange=async e=>{
 const srt=e.target.files[0];if(!srt||active)return;if(srt.size>100000){status('limit');return;}const ticket=generation;importing=true;controls();
 try{const parsed=SubtitleFormat.parse(await srt.text());if(ticket!==generation)return;cues=parsed;clear();rows();preview();status('imported');}catch(error){if(ticket===generation)status(copy[lang][error.message]?error.message:'format');}finally{if(ticket===generation){importing=false;controls();}}
};
['subStyle','subPosition','subSize'].forEach(id=>$(id).onchange=changed);video.ontimeupdate=preview;video.onseeked=preview;window.addEventListener('resize',preview);
$('subCancel').onclick=()=>{const job=active;if(!job)return;active=null;job.controller.abort();if(job.engine)job.engine.terminate();window.DroopAnalytics?.finish('cancel');status('canceled');controls();};
$('subExport').onclick=async()=>{
 if(!file||active||importing||!duration)return;let valid;try{valid=SubtitleFormat.validate(cues,duration);}catch(error){status(copy[lang][error.message]?error.message:'format');return;}
 const source=file,d=SubtitleFormat.size(video.videoWidth,video.videoHeight),script=SubtitleFormat.ass(valid,d.w,d.h,$('subStyle').value,$('subPosition').value,$('subSize').value);
 const job={controller:new AbortController(),engine:null};active=job;window.DroopAnalytics?.start();video.pause();clear();status('preparing');controls();const check=()=>{if(active!==job)throw Error('CANCELED');};
 try{const engine=await DroopVideoEngine.load(job,()=>active===job);check();const response=await fetch('assets/fonts/DejaVuSans.ttf',{signal:job.controller.signal});if(!response.ok)throw Error('FONT');const font=new Uint8Array(await response.arrayBuffer());check();await engine.createDir('fonts');await engine.writeFile('fonts/DejaVuSans.ttf',font);check();await engine.writeFile('captions.ass',new TextEncoder().encode(script));const input=new Uint8Array(await source.arrayBuffer());check();await engine.writeFile('input',input);check();status('processing');
 const code=await engine.exec(['-i','input','-vf',`scale=${d.w}:${d.h},setsar=1,ass=captions.ass:fontsdir=fonts`,'-map','0:v:0','-map','0:a:0?','-c:v','libx264','-preset','ultrafast','-crf','22','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart','-y','output.mp4']);check();if(code!==0)throw Error('EXPORT');const output=await engine.readFile('output.mp4');check();if(!(output instanceof Uint8Array)||output.length<32)throw Error('EMPTY');const blob=new Blob([output],{type:'video/mp4'});outputURL=URL.createObjectURL(blob);$('subOutput').src=outputURL;$('subDownload').href=outputURL;$('subDownload').download=`${source.name.replace(/\.[^.]+$/,'').replace(/[<>:"/\\|?*\u0000-\u001F]/g,'-').slice(0,100)}-subtitled.mp4`;$('subResultInfo').textContent=`MP4 · ${d.w} × ${d.h} · ${bytes(blob.size)}`;$('subResult').hidden=false;window.DroopAnalytics?.finish('complete');status('ready');
 }catch(error){if(active===job){console.error('[droop subtitles]',error);window.DroopAnalytics?.finish('error');status('failed');}}finally{if(job.engine)job.engine.terminate();if(active===job){active=null;controls();}}
};language();
})();
