const compressInput=document.querySelector('#compressFileInput');
const compressDropZone=document.querySelector('#compressDropZone');
const compressFileInfo=document.querySelector('#compressFileInfo');
const targetSizeInput=document.querySelector('#targetSize');
const targetUnitSelect=document.querySelector('#targetUnit');
const compressButton=document.querySelector('#compressButton');
const compressStatus=document.querySelector('#compressStatus');
const compressResult=document.querySelector('#compressResult');
const originalSizeEl=document.querySelector('#originalSize');
const compressedSizeEl=document.querySelector('#compressedSize');
const compressedQualityEl=document.querySelector('#compressedQuality');
const compressedDimensionsEl=document.querySelector('#compressedDimensions');
const compressedPreview=document.querySelector('#compressedPreview');
const compressDownloadButton=document.querySelector('#compressDownloadButton');
const idleButton=compressButton.textContent;
const isEs=()=>((localStorage.getItem('droop-language')||localStorage.getItem('droop-lang')||navigator.language||'en').toLowerCase().startsWith('es'));
const tr=(en,es)=>isEs()?es:en;
let compressFile=null,compressedBlob=null,compressedObjectUrl=null;
function prettyBytes(bytes){if(bytes<1024)return`${bytes} B`;if(bytes<1048576)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1024/1024).toFixed(2)} MB`;}
function targetBytes(){const value=Number(targetSizeInput.value);if(!Number.isFinite(value)||value<=0)return 0;return targetUnitSelect.value==='KB'?value*1024:value*1024*1024;}
function setCompressFile(file){if(!file)return;if(!file.type.startsWith('image/')){compressInput.value='';return alert(tr('Please choose an image file.','Elegí un archivo de imagen.'));}compressFile=file;compressedBlob=null;if(compressedObjectUrl){URL.revokeObjectURL(compressedObjectUrl);compressedObjectUrl=null;}compressButton.disabled=false;compressResult.hidden=true;compressStatus.hidden=true;compressFileInfo.hidden=false;compressFileInfo.textContent=`${file.name} · ${prettyBytes(file.size)}`;}
compressInput.addEventListener('click',()=>{compressInput.value='';});compressInput.addEventListener('change',event=>setCompressFile(event.target.files[0]));
['dragenter','dragover'].forEach(type=>compressDropZone.addEventListener(type,event=>{event.preventDefault();compressDropZone.classList.add('dragging');}));['dragleave','drop'].forEach(type=>compressDropZone.addEventListener(type,event=>{event.preventDefault();compressDropZone.classList.remove('dragging');}));compressDropZone.addEventListener('drop',event=>setCompressFile(event.dataTransfer.files[0]));
function canvasToBlob(canvas,quality){return new Promise(resolve=>canvas.toBlob(resolve,'image/jpeg',quality));}
async function loadImage(file){const url=URL.createObjectURL(file);try{const image=new Image();await new Promise((resolve,reject)=>{image.onload=resolve;image.onerror=reject;image.src=url;});return image;}finally{URL.revokeObjectURL(url);}}
async function bestQualityUnderTarget(canvas,maxBytes){const minimumQuality=.08,maximumQuality=.95;let low=minimumQuality,high=maximumQuality,bestBlob=null,bestQuality=minimumQuality;const minimumBlob=await canvasToBlob(canvas,minimumQuality);if(!minimumBlob||minimumBlob.size>maxBytes)return null;for(let i=0;i<10;i+=1){const quality=(low+high)/2,blob=await canvasToBlob(canvas,quality);if(!blob)break;if(blob.size<=maxBytes){bestBlob=blob;bestQuality=quality;low=quality}else high=quality;}return{blob:bestBlob||minimumBlob,quality:bestBlob?bestQuality:minimumQuality};}
async function compressWithResizeFallback(image,maxBytes){let width=image.naturalWidth,height=image.naturalHeight;for(let resizeStep=0;resizeStep<7;resizeStep+=1){const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(width));canvas.height=Math.max(1,Math.round(height));const context=canvas.getContext('2d');context.imageSmoothingEnabled=true;context.imageSmoothingQuality='high';context.drawImage(image,0,0,canvas.width,canvas.height);const result=await bestQualityUnderTarget(canvas,maxBytes);if(result)return{...result,width:canvas.width,height:canvas.height,resized:resizeStep>0};width*=.82;height*=.82;}return null;}
compressButton.addEventListener('click',async()=>{if(!compressFile)return;const maxBytes=targetBytes();if(!maxBytes){compressStatus.hidden=false;compressStatus.textContent=tr('Enter a valid target size.','Ingresá un tamaño objetivo válido.');return;}compressButton.disabled=true;compressButton.textContent=tr('Finding best quality…','Buscando la mejor calidad…');compressStatus.hidden=false;compressStatus.textContent=tr('Processing…','Procesando…');compressResult.hidden=true;try{const image=await loadImage(compressFile),result=await compressWithResizeFallback(image,maxBytes);if(!result)throw new Error(tr('Could not reach that target size without making the image extremely small.','No se pudo alcanzar ese tamaño sin reducir demasiado la imagen.'));compressedBlob=result.blob;if(compressedObjectUrl)URL.revokeObjectURL(compressedObjectUrl);compressedObjectUrl=URL.createObjectURL(compressedBlob);compressedPreview.src=compressedObjectUrl;originalSizeEl.textContent=prettyBytes(compressFile.size);compressedSizeEl.textContent=prettyBytes(compressedBlob.size);compressedQualityEl.textContent=`${Math.round(result.quality*100)}%`;compressedDimensionsEl.textContent=`${result.width} × ${result.height}${result.resized?tr(' · resized',' · redimensionada'):''}`;const savings=Math.max(0,100-(compressedBlob.size/compressFile.size)*100);compressStatus.textContent=tr(`Ready ✓ ${savings.toFixed(0)}% smaller`,`Listo ✓ ${savings.toFixed(0)}% más chica`);compressResult.hidden=false;compressResult.scrollIntoView({behavior:'smooth',block:'nearest'});}catch(error){compressStatus.textContent=error.message||tr('Something went wrong while compressing the image.','Ocurrió un error al comprimir la imagen.');}finally{compressButton.disabled=false;compressButton.textContent=idleButton;}});
compressDownloadButton.addEventListener('click',()=>{if(!compressedBlob||!compressFile)return;const link=document.createElement('a'),url=URL.createObjectURL(compressedBlob),baseName=compressFile.name.replace(/\.[^.]+$/,'')||'image';link.href=url;link.download=`${baseName}-under-${targetSizeInput.value}${targetUnitSelect.value.toLowerCase()}.jpg`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);});