(()=>{'use strict';
const copy={
en:{title:'droop account — Creator workspace',meta:'Sign in to Droop to save presets and keep creator workflows together.',navTools:'Tools',navHome:'Home',privacyPill:'Local processing · No uploads',eyebrow:'DROOP ACCOUNT',heroTitle:'Your creator<br>workspace.',heroCopy:'Save reusable settings across Droop while your images, video and audio still stay on your device.',getStarted:'GET STARTED',password:'Password',recoveryLabel:'PASSWORD RECOVERY',recoveryTitle:'Choose a new password.',newPassword:'New password',updatePassword:'Update password',signedInLabel:'SIGNED IN',accountTitle:'Your Droop account.',planLabel:'PLAN',presetPrivacy:'Saved presets contain settings only. Your media files are not uploaded to your account.',displayName:'Display name',saveName:'Save account name',changePassword:'Change password',passwordPlaceholder:'At least 8 characters',savedPresets:'Saved presets',emptyPresetsShort:'No presets saved yet.',openTools:'Open tools',signOut:'Sign out',footer1:'droop · Everything you need before you post.',footer2:'Private browser-based tools.',privacyLink:'Privacy',comparePlans:'Compare Free and Pro →',signIn:'Sign in',createAccount:'Create account',toSignup:'New to Droop? Create an account',toSignin:'Already have an account? Sign in',forgot:'Forgot password?',unavailable:'Account setup is unavailable right now.',loading:'Loading your workspace…',working:'Working…',passwordMin:'Use at least 8 characters for your password.',confirmEmail:'Check your email to confirm your Droop account.',signedIn:'You are signed in.',nameTooLong:'Use at most 60 characters.',saving:'Saving…',nameSaved:'Account name saved.',updating:'Updating…',passwordUpdated:'Password updated.',enterEmail:'Enter your email first, then choose Forgot password.',sendingReset:'Sending password reset email…',resetSent:'Password reset email sent. Check your inbox.',deleteConfirm:'Delete this preset?',deleting:'Deleting preset…',presetDeleted:'Preset deleted.',signedOut:'Signed out.',emptyPresets:'No presets saved yet. Open a tool, choose your settings and save one.',openTool:'Open tool',delete:'Delete',creator:'Droop creator'},
es:{title:'cuenta droop — Tu espacio de trabajo',meta:'Iniciá sesión en Droop para guardar presets y mantener juntos tus flujos de trabajo.',navTools:'Herramientas',navHome:'Inicio',privacyPill:'Procesamiento local · Sin subidas',eyebrow:'CUENTA DROOP',heroTitle:'Tu espacio<br>de creador.',heroCopy:'Guardá configuraciones reutilizables en Droop mientras tus imágenes, videos y audios siguen quedándose en tu dispositivo.',getStarted:'EMPEZAR',password:'Contraseña',recoveryLabel:'RECUPERAR CONTRASEÑA',recoveryTitle:'Elegí una nueva contraseña.',newPassword:'Nueva contraseña',updatePassword:'Actualizar contraseña',signedInLabel:'SESIÓN INICIADA',accountTitle:'Tu cuenta de Droop.',planLabel:'PLAN',presetPrivacy:'Los presets guardan configuraciones solamente. Tus archivos multimedia no se suben a tu cuenta.',displayName:'Nombre visible',saveName:'Guardar nombre',changePassword:'Cambiar contraseña',passwordPlaceholder:'Mínimo 8 caracteres',savedPresets:'Presets guardados',emptyPresetsShort:'Todavía no guardaste presets.',openTools:'Abrir herramientas',signOut:'Cerrar sesión',footer1:'droop · Todo lo que necesitás antes de publicar.',footer2:'Herramientas privadas desde tu navegador.',privacyLink:'Privacidad',comparePlans:'Comparar Free y Pro →',signIn:'Iniciar sesión',createAccount:'Crear cuenta',toSignup:'¿Sos nuevo en Droop? Creá una cuenta',toSignin:'¿Ya tenés cuenta? Iniciá sesión',forgot:'¿Olvidaste tu contraseña?',unavailable:'La cuenta no está disponible en este momento.',loading:'Cargando tu espacio…',working:'Procesando…',passwordMin:'Usá al menos 8 caracteres para tu contraseña.',confirmEmail:'Revisá tu correo para confirmar tu cuenta de Droop.',signedIn:'Sesión iniciada.',nameTooLong:'Usá como máximo 60 caracteres.',saving:'Guardando…',nameSaved:'Nombre de cuenta guardado.',updating:'Actualizando…',passwordUpdated:'Contraseña actualizada.',enterEmail:'Primero ingresá tu email y después tocá “¿Olvidaste tu contraseña?”.',sendingReset:'Enviando correo de recuperación…',resetSent:'Correo de recuperación enviado. Revisá tu bandeja.',deleteConfirm:'¿Eliminar este preset?',deleting:'Eliminando preset…',presetDeleted:'Preset eliminado.',signedOut:'Sesión cerrada.',emptyPresets:'Todavía no guardaste presets. Abrí una herramienta, elegí tus ajustes y guardá uno.',openTool:'Abrir herramienta',delete:'Eliminar',creator:'Creador de Droop'}
};
const toolNames={'make-it-fit':{en:'Make It Fit',es:'Ajustar al formato'},'under-x-mb':{en:'Under X MB',es:'Menos de X MB'},'release-pack':{en:'Release Pack',es:'Pack de lanzamiento'},'metadata-cleaner':{en:'Metadata Cleaner',es:'Limpiar metadatos'},'image-converter':{en:'Image Converter',es:'Convertir imagen'},'background-remover':{en:'Background Remover',es:'Quitar fondo'},'image-upscaler':{en:'Image Upscaler',es:'Ampliar imagen'},'video-cropper':{en:'Video Cropper',es:'Recortar video'},'video-under-x-mb':{en:'Video Under X MB',es:'Video en menos de X MB'},'video-trimmer':{en:'Video Trimmer',es:'Recortar video'},'video-to-gif':{en:'Video to GIF',es:'Video a GIF'},'subtitle-burner':{en:'Subtitle Burner',es:'Agregar subtítulos'},'extract-audio':{en:'Extract Audio',es:'Extraer audio'},'audio-converter':{en:'Audio Converter',es:'Convertir audio'},'audio-trimmer':{en:'Audio Trimmer',es:'Recortar audio'},'thumbnail-maker':{en:'Thumbnail Maker',es:'Creador de miniaturas'},'safe-zones':{en:'Social Safe Zones',es:'Zonas seguras para redes'}};
const getLang=()=>{try{const saved=localStorage.getItem('droop-language');if(saved==='en'||saved==='es')return saved;}catch(_){}return(navigator.language||'').toLowerCase().startsWith('es')?'es':'en';};
let lang=getLang(),signup=false,recoveryMode=false,currentSession=null;
const params=new URLSearchParams(location.search);signup=params.get('mode')==='signup';if(params.get('recovery')==='1')recoveryMode=true;
const t=key=>copy[lang][key]??copy.en[key]??key,cfg=window.DroopSupabaseConfig||{},LIMITS={free:5,pro:100};
const ui={form:document.querySelector('#auth-form'),email:document.querySelector('#auth-email'),password:document.querySelector('#auth-password'),submit:document.querySelector('#auth-submit'),switcher:document.querySelector('#auth-switch'),forgot:document.querySelector('#forgot-password'),mode:document.querySelector('#auth-mode'),status:document.querySelector('#auth-status'),signed:document.querySelector('#signed-in'),identity:document.querySelector('#account-email'),plan:document.querySelector('#account-plan'),usage:document.querySelector('#account-usage'),presets:document.querySelector('#account-presets'),accountStatus:document.querySelector('#account-status'),signout:document.querySelector('#signout'),guest:document.querySelector('#guest-view'),recovery:document.querySelector('#recovery-view'),recoveryForm:document.querySelector('#recovery-form'),recoveryPassword:document.querySelector('#recovery-password'),recoveryStatus:document.querySelector('#recovery-status'),profileForm:document.querySelector('#profile-form'),displayName:document.querySelector('#display-name'),profileStatus:document.querySelector('#profile-status'),passwordForm:document.querySelector('#password-form'),newPassword:document.querySelector('#new-password'),passwordStatus:document.querySelector('#password-status'),lang:document.querySelector('#account-lang')};
function setAuthMode(updateUrl=true){if(!ui.mode||!ui.submit||!ui.switcher||!ui.forgot)return;ui.mode.textContent=signup?t('createAccount'):t('signIn');ui.submit.textContent=signup?t('createAccount'):t('signIn');ui.password.autocomplete=signup?'new-password':'current-password';ui.switcher.textContent=signup?t('toSignin'):t('toSignup');ui.forgot.textContent=t('forgot');ui.forgot.hidden=signup;if(updateUrl&&!recoveryMode){const u=new URL(location.href);if(signup)u.searchParams.set('mode','signup');else u.searchParams.delete('mode');history.replaceState({},'',u.pathname+(u.searchParams.toString()?'?'+u.searchParams.toString():''));}}
function applyLanguage(){document.documentElement.lang=lang;document.title=t('title');const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=t('meta');document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n);});document.querySelectorAll('[data-i18n-html]').forEach(el=>{el.innerHTML=t(el.dataset.i18nHtml);});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{el.placeholder=t(el.dataset.i18nPlaceholder);});if(ui.lang){ui.lang.textContent=lang==='es'?'EN':'ES';ui.lang.setAttribute('aria-label',lang==='es'?'Cambiar a inglés':'Switch to Spanish');}setAuthMode(false);}
const state=(el,msg,error=false)=>{if(!el)return;el.textContent=msg||'';el.dataset.state=error?'error':'ok';},say=(m,e=false)=>state(ui.status,m,e),accountSay=(m,e=false)=>state(ui.accountStatus,m,e),profileSay=(m,e=false)=>state(ui.profileStatus,m,e),passwordSay=(m,e=false)=>state(ui.passwordStatus,m,e),recoverySay=(m,e=false)=>state(ui.recoveryStatus,m,e);
const escapeHtml=value=>String(value).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),toolHref=slug=>slug==='extract-audio'?'/extract-audio/':`/${encodeURIComponent(slug)}.html`,toolLabel=slug=>toolNames[slug]?.[lang]||String(slug||'tool').split('-').map(x=>x.charAt(0).toUpperCase()+x.slice(1)).join(' ');
applyLanguage();
if(!ui.form||!window.supabase||!cfg.url||!cfg.anonKey){say(t('unavailable'),true);return;}
const client=window.supabase.createClient(cfg.url,cfg.anonKey);
async function loadAccount(session){if(!session)return;ui.identity.textContent=session.user.email||t('creator');accountSay(t('loading'));const [{data:profile,error:profileError},{data:presets,error:presetError}]=await Promise.all([client.from('profiles').select('plan,email,display_name').eq('id',session.user.id).single(),client.from('presets').select('id,tool_slug,name,updated_at').eq('user_id',session.user.id).order('updated_at',{ascending:false})]);if(profileError){accountSay(profileError.message,true);return;}if(presetError){accountSay(presetError.message,true);return;}const plan=profile?.plan==='pro'?'pro':'free',items=presets||[];ui.displayName.value=profile?.display_name||'';ui.plan.textContent=plan.toUpperCase();ui.usage.textContent=`${items.length} / ${LIMITS[plan]}`;ui.presets.innerHTML=!items.length?`<p class="account-empty">${escapeHtml(t('emptyPresets'))}</p>`:items.map(p=>`<div class="account-preset-row" data-id="${p.id}"><div><strong>${escapeHtml(p.name)}</strong><small>${escapeHtml(toolLabel(p.tool_slug))}</small></div><a href="${toolHref(p.tool_slug)}">${escapeHtml(t('openTool'))}</a><button type="button" data-delete="${p.id}" aria-label="${escapeHtml(t('delete'))} ${escapeHtml(p.name)}">${escapeHtml(t('delete'))}</button></div>`).join('');accountSay('');}
async function render(session){currentSession=session||null;const on=!!session;ui.guest.hidden=on||recoveryMode;ui.signed.hidden=!on||recoveryMode;ui.recovery.hidden=!recoveryMode;if(on&&!recoveryMode)await loadAccount(session);}
ui.lang?.addEventListener('click',()=>{lang=lang==='es'?'en':'es';try{localStorage.setItem('droop-language',lang);}catch(_){}applyLanguage();if(currentSession&&!recoveryMode)loadAccount(currentSession);});
ui.switcher.addEventListener('click',()=>{signup=!signup;setAuthMode(true);say('');});
ui.form.addEventListener('submit',async e=>{e.preventDefault();ui.submit.disabled=true;say(t('working'));const email=ui.email.value.trim(),password=ui.password.value;if(password.length<8){say(t('passwordMin'),true);ui.submit.disabled=false;return;}const result=signup?await client.auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/account.html'}}):await client.auth.signInWithPassword({email,password});if(result.error)say(result.error.message,true);else if(signup&&!result.data.session){window.DroopAnalytics?.track?.('signup_success');say(t('confirmEmail'));}else{window.DroopAnalytics?.track?.(signup?'signup_success':'login_success');say(t('signedIn'));await render(result.data.session);}ui.submit.disabled=false;});
ui.profileForm.addEventListener('submit',async e=>{e.preventDefault();const name=ui.displayName.value.trim();if(name.length>60){profileSay(t('nameTooLong'),true);return;}const button=ui.profileForm.querySelector('button');button.disabled=true;profileSay(t('saving'));const {data:userData,error:userError}=await client.auth.getUser();if(userError||!userData.user){profileSay(userError?.message||t('unavailable'),true);button.disabled=false;return;}const {error}=await client.rpc('set_my_display_name',{p_display_name:name});if(error)profileSay(error.message,true);else profileSay(t('nameSaved'));button.disabled=false;});
ui.passwordForm.addEventListener('submit',async e=>{e.preventDefault();const password=ui.newPassword.value;if(password.length<8){passwordSay(t('passwordMin'),true);return;}const button=ui.passwordForm.querySelector('button');button.disabled=true;passwordSay(t('updating'));const {error}=await client.auth.updateUser({password});if(error)passwordSay(error.message,true);else{ui.newPassword.value='';passwordSay(t('passwordUpdated'));}button.disabled=false;});
ui.forgot.addEventListener('click',async()=>{const email=ui.email.value.trim();if(!email){say(t('enterEmail'),true);return;}ui.forgot.disabled=true;say(t('sendingReset'));const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/account.html'});if(error)say(error.message,true);else say(t('resetSent'));ui.forgot.disabled=false;});
ui.recoveryForm.addEventListener('submit',async e=>{e.preventDefault();const password=ui.recoveryPassword.value;if(password.length<8){recoverySay(t('passwordMin'),true);return;}const button=ui.recoveryForm.querySelector('button');button.disabled=true;recoverySay(t('updating'));const {error}=await client.auth.updateUser({password});if(error)recoverySay(error.message,true);else{recoveryMode=false;history.replaceState({},'',location.pathname);recoverySay('');const {data}=await client.auth.getSession();await render(data.session);accountSay(t('passwordUpdated'));}button.disabled=false;});
ui.presets.addEventListener('click',async e=>{const button=e.target.closest('[data-delete]');if(!button)return;if(!confirm(t('deleteConfirm')))return;button.disabled=true;accountSay(t('deleting'));const {error}=await client.from('presets').delete().eq('id',button.dataset.delete);if(error){accountSay(error.message,true);button.disabled=false;return;}const {data}=await client.auth.getSession();await loadAccount(data.session);accountSay(t('presetDeleted'));});
ui.signout.addEventListener('click',async()=>{await client.auth.signOut();await render(null);say(t('signedOut'));});
client.auth.onAuthStateChange((event,session)=>{if(event==='PASSWORD_RECOVERY'){recoveryMode=true;render(session);return;}if(!recoveryMode)render(session);});
(async()=>{const {data,error}=await client.auth.getSession();if(error){say(error.message,true);return;}await render(data.session);})();
})();