const presets={youtube:{name:'YouTube Thumbnail',width:1280,height:720},'instagram-post':{name:'Instagram Post',width:1080,height:1080},'instagram-story':{name:'Instagram Story',width:1080,height:1920},spotify:{name:'Spotify Cover',width:3000,height:3000},'discord-avatar':{name:'Discord Avatar',width:512,height:512}};
const input=document.querySelector('#fileInput'),drop=document.querySelector('#dropZone'),info=document.querySelector('#fileInfo'),select=document.querySelector('#presetSelect'),processBtn=document.querySelector('#processButton'),result=document.querySelector('#result'),canvas=document.querySelector('#previewCanvas'),ctx=canvas.getContext('2d'),downloadBtn=document.querySelector('#downloadButton');
let currentFile=null;
function setFile(file){if(!file||!file.type.startsWith('image/')){alert('Please choose an image file.');return}currentFile=file;info.hidden=false;info.textContent=`${file.name} · ${(file.size/1024/1024).toFixed(2)} MB`;processBtn.disabled=false;result.hidden=true}
input.addEventListener('change',e=>setFile(e.target.files[0]));
['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('dragging')}));
['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('dragging')}));
drop.addEventListener('drop',e=>setFile(e.dataTransfer.files[0]));
processBtn.addEventListener('click',()=>{if(!currentFile)return;const preset=presets[select.value];const img=new Image();const url=URL.createObjectURL(currentFile);img.onload=()=>{canvas.width=preset.width;canvas.height=preset.height;const sourceRatio=img.width/img.height,targetRatio=preset.width/preset.height;let sx=0,sy=0,sw=img.width,sh=img.height;if(sourceRatio>targetRatio){sw=img.height*targetRatio;sx=(img.width-sw)/2}else{sh=img.width/targetRatio;sy=(img.height-sh)/2}ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,sx,sy,sw,sh,0,0,preset.width,preset.height);document.querySelector('#resultPreset').textContent=preset.name;document.querySelector('#resultDimensions').textContent=`${preset.width} × ${preset.height} JPG`;result.hidden=false;result.scrollIntoView({behavior:'smooth',block:'nearest'});URL.revokeObjectURL(url)};img.src=url});
downloadBtn.addEventListener('click',()=>{const preset=presets[select.value];canvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`creatortools-${select.value}-${preset.width}x${preset.height}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/jpeg',.92)});