(()=>{'use strict';
const copy={
  en:{
    html:'en',title:'droop — Everything you need before you post',meta:'Droop helps creators resize, compress, convert and prepare images, video and audio directly in the browser.',
    nav:['Tools','Image','Video','Audio','Social'],privacy:'Local processing · No uploads',eyebrow:'DROOP · TOOLS FOR CREATORS',hero:'Everything you need<br>before you post.',heroCopy:'Images, video and audio — ready to post without the technical headache. Private, simple, right in your browser.',
    toolsLabel:'DROOP TOOLS',catalogTitle:'What do you want to make?',catalogCopy:"Pick what you're working with. We'll handle the technical stuff.",search:'Search tools…',tabs:['All','Image','Video','Audio','Social'],empty:'No tools found. Try another search.',open:'Open tool',rebuilding:'Rebuilding',
    whyLabel:'WHY DROOP',whyTitle:'Made to get out of your way.',why:[['Private by default','Your media stays on your device for supported local tools.'],['No technical guesswork','Choose what you need to make instead of memorizing formats and dimensions.'],['Fast workflow','Open a tool, drop your file, make the change and download the result.'],['Built for creators','Useful presets and workflows for social, video, music and everyday posting.']],
    footer:['droop · Everything you need before you post.','Private browser-based tools.'],langLabel:'Language',langOther:'ES'
  },
  es:{
    html:'es',title:'droop — Todo lo que necesitás antes de publicar',meta:'Droop ayuda a creadores a redimensionar, comprimir, convertir y preparar imágenes, video y audio directamente en el navegador.',
    nav:['Herramientas','Imagen','Video','Audio','Social'],privacy:'Procesamiento local · Sin subidas',eyebrow:'DROOP · HERRAMIENTAS PARA CREADORES',hero:'Todo lo que necesitás<br>antes de publicar.',heroCopy:'Imágenes, video y audio listos para publicar, sin vueltas técnicas. Privado, simple y directo en tu navegador.',
    toolsLabel:'HERRAMIENTAS DROOP',catalogTitle:'¿Qué querés hacer?',catalogCopy:'Elegí con qué estás trabajando. Nosotros nos ocupamos de lo técnico.',search:'Buscar herramientas…',tabs:['Todo','Imagen','Video','Audio','Social'],empty:'No encontramos herramientas. Probá con otra búsqueda.',open:'Abrir herramienta',rebuilding:'En desarrollo',
    whyLabel:'POR QUÉ DROOP',whyTitle:'Hecho para no meterse en tu camino.',why:[['Privado por defecto','Tus archivos se quedan en tu dispositivo en las herramientas con procesamiento local.'],['Sin adivinar cosas técnicas','Elegí lo que querés hacer en vez de memorizar formatos y dimensiones.'],['Flujo rápido','Abrí una herramienta, soltá tu archivo, hacé el cambio y descargá el resultado.'],['Hecho para creadores','Presets y flujos útiles para redes, video, música y publicaciones de todos los días.']],
    footer:['droop · Todo lo que necesitás antes de publicar.','Herramientas privadas que funcionan en tu navegador.'],langLabel:'Idioma',langOther:'EN'
  }
};
const tools=[
{cat:'image',icon:'✦',title:{en:'Make It Fit',es:'Ajustar al formato'},desc:{en:'Resize and crop for YouTube, Instagram, Spotify and more.',es:'Redimensioná y recortá para YouTube, Instagram, Spotify y más.'},href:'make-it-fit.html',tag:{en:'Popular',es:'Popular'}},
{cat:'image',icon:'↓',title:{en:'Under X MB',es:'Menos de X MB'},desc:{en:'Hit a file-size limit automatically without the guesswork.',es:'Llegá automáticamente al límite de peso que necesitás.'},href:'under-x-mb.html',tag:{en:'Smart',es:'Inteligente'}},
{cat:'image',icon:'▦',title:{en:'Release Pack',es:'Pack de lanzamiento'},desc:{en:'Turn one artwork into a complete set of ready-to-post sizes.',es:'Convertí una portada en un pack completo de tamaños listos para publicar.'},href:'release-pack.html',tag:{en:'Workflow',es:'Flujo'}},
{cat:'image',icon:'◇',title:{en:'Metadata Cleaner',es:'Limpiar metadatos'},desc:{en:'Create a clean copy without common embedded image metadata.',es:'Creá una copia limpia sin los metadatos comunes de la imagen.'},href:'metadata-cleaner.html',tag:{en:'Privacy',es:'Privacidad'}},
{cat:'image',icon:'↔',title:{en:'Image Converter',es:'Convertir imagen'},desc:{en:'Convert JPG, PNG and WebP directly in your browser.',es:'Convertí JPG, PNG y WebP directamente en tu navegador.'},href:'image-converter.html',tag:{en:'Stable',es:'Estable'}},
{cat:'video',icon:'◉',title:{en:'Video Under X MB',es:'Video en menos de X MB'},desc:{en:'Compress a video toward the maximum size you choose.',es:'Comprimí un video hasta el tamaño máximo que elijas.'},href:'video-under-x-mb.html',tag:{en:'Beta',es:'Beta'}},
{cat:'video',icon:'✂',title:{en:'Video Trimmer',es:'Recortar video'},desc:{en:'Cut out exactly the part of a video you want to keep.',es:'Cortá exactamente la parte del video que querés conservar.'},href:'video-trimmer.html',tag:{en:'New',es:'Nuevo'}},
{cat:'audio',icon:'♫',title:{en:'Extract Audio',es:'Extraer audio'},desc:{en:'Turn a video into an MP3 or WAV file.',es:'Convertí el audio de un video en MP3 o WAV.'},href:'extract-audio/',tag:{en:'Stable',es:'Estable'}},
{cat:'audio',icon:'⇄',title:{en:'Audio Converter',es:'Convertir audio'},desc:{en:'Convert common audio formats to MP3 or WAV.',es:'Convertí formatos de audio comunes a MP3 o WAV.'},href:'audio-converter.html',tag:{en:'Stable',es:'Estable'}},
{cat:'audio',icon:'✂',title:{en:'Audio Trimmer',es:'Recortar audio'},desc:{en:'Trim songs, samples, voice notes and podcast clips.',es:'Recortá canciones, samples, notas de voz y fragmentos de podcast.'},href:'audio-trimmer.html',tag:{en:'New',es:'Nuevo'}},
{cat:'social',icon:'▣',title:{en:'Social Safe Zones',es:'Zonas seguras para redes'},desc:{en:'Preview where app UI can cover vertical content.',es:'Previsualizá dónde la interfaz puede tapar contenido vertical.'},href:'safe-zones.html',tag:{en:'Social',es:'Social'}},
{cat:'image',icon:'◌',title:{en:'Background Remover',es:'Quitar fondo'},desc:{en:'A lighter, safer version is being rebuilt.',es:'Estamos reconstruyendo una versión más liviana y segura.'},href:'#background-remover',tag:{en:'Coming soon',es:'Próximamente'},disabled:true}
];
function init(){
  let lang=localStorage.getItem('droop-language')||((navigator.language||'').toLowerCase().startsWith('es')?'es':'en');
  const old=document.querySelector('#tool-catalog')||document.querySelector('.workflow');if(!old)return;
  old.id='tool-catalog';
  old.innerHTML='<div class="catalog-head"><div><p class="section-label"></p><h2 id="catalog-title"></h2><p class="catalog-copy"></p></div><div class="catalog-search-wrap"><span>⌕</span><input id="catalogSearch" type="search" autocomplete="off"></div></div><div class="catalog-tabs" role="tablist"><button class="active" data-filter="all"></button><button data-filter="image"></button><button data-filter="video"></button><button data-filter="audio"></button><button data-filter="social"></button></div><div class="catalog-grid" id="catalogGrid"></div><div class="catalog-empty" id="catalogEmpty" hidden></div>';
  const grid=old.querySelector('#catalogGrid'),search=old.querySelector('#catalogSearch'),empty=old.querySelector('#catalogEmpty'),tabs=[...old.querySelectorAll('.catalog-tabs button')];let filter='all';
  const header=document.querySelector('.site-header');let switcher=document.querySelector('.lang-switch');if(!switcher&&header){switcher=document.createElement('button');switcher.className='lang-switch';switcher.type='button';header.appendChild(switcher);}
  function render(){const t=copy[lang],q=search.value.trim().toLowerCase();const shown=tools.filter(x=>(filter==='all'||x.cat===filter)&&(!q||`${x.title[lang]} ${x.desc[lang]} ${x.cat}`.toLowerCase().includes(q)));grid.innerHTML=shown.map(x=>`<a class="catalog-card ${x.disabled?'is-disabled':''}" href="${x.href}" data-cat="${x.cat}"><div class="catalog-icon">${x.icon}</div><div class="catalog-card-top"><span class="catalog-category">${x.cat}</span><span class="catalog-tag">${x.tag[lang]}</span></div><h3>${x.title[lang]}</h3><p>${x.desc[lang]}</p><span class="catalog-open">${x.disabled?t.rebuilding:t.open} <b>↗</b></span></a>`).join('');empty.hidden=shown.length>0;}
  function apply(){const t=copy[lang];document.documentElement.lang=t.html;document.title=t.title;const meta=document.querySelector('meta[name="description"]');if(meta)meta.content=t.meta;const brand=document.querySelector('.brand');if(brand){brand.textContent='droop';brand.setAttribute('aria-label','Droop home');}
    const nav=document.querySelector('.top-nav');if(nav){nav.innerHTML=`<a href="#tool-catalog">${t.nav[0]}</a><a href="#tool-catalog" data-jump="image">${t.nav[1]}</a><a href="#tool-catalog" data-jump="video">${t.nav[2]}</a><a href="#tool-catalog" data-jump="audio">${t.nav[3]}</a><a href="safe-zones.html">${t.nav[4]}</a>`;nav.querySelectorAll('[data-jump]').forEach(a=>a.addEventListener('click',()=>{const b=old.querySelector(`[data-filter="${a.dataset.jump}"]`);setTimeout(()=>b?.click(),80);}));}
    const privacy=document.querySelector('.privacy-pill');if(privacy)privacy.textContent=t.privacy;const eyebrow=document.querySelector('.eyebrow');if(eyebrow)eyebrow.textContent=t.eyebrow;const heroTitle=document.querySelector('#hero-title');if(heroTitle)heroTitle.innerHTML=t.hero;const heroCopy=document.querySelector('.hero-copy');if(heroCopy)heroCopy.textContent=t.heroCopy;
    old.querySelector('.section-label').textContent=t.toolsLabel;old.querySelector('#catalog-title').textContent=t.catalogTitle;old.querySelector('.catalog-copy').textContent=t.catalogCopy;search.placeholder=t.search;tabs.forEach((b,i)=>b.textContent=t.tabs[i]);empty.textContent=t.empty;
    const why=[...document.querySelectorAll('.workflow')].find(x=>x!==old);if(why){why.setAttribute('aria-label',lang==='es'?'Por qué Droop':'Why Droop');const label=why.querySelector('.section-label'),h2=why.querySelector('h2'),cards=[...why.querySelectorAll('article')];if(label)label.textContent=t.whyLabel;if(h2)h2.textContent=t.whyTitle;cards.forEach((card,i)=>{const h=card.querySelector('h3'),p=card.querySelector('p');if(h)h.textContent=t.why[i][0];if(p)p.textContent=t.why[i][1];});}
    const foot=[...document.querySelectorAll('footer span')];if(foot[0])foot[0].textContent=t.footer[0];if(foot[1])foot[1].textContent=t.footer[1];if(switcher){switcher.textContent=t.langOther;switcher.setAttribute('aria-label',`${t.langLabel}: ${t.langOther}`);switcher.title=`${t.langLabel}: ${t.langOther}`;}render();}
  tabs.forEach(btn=>btn.addEventListener('click',()=>{filter=btn.dataset.filter;tabs.forEach(x=>x.classList.toggle('active',x===btn));render();}));search.addEventListener('input',render);switcher?.addEventListener('click',()=>{lang=lang==='en'?'es':'en';localStorage.setItem('droop-language',lang);apply();});apply();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();