(()=>{'use strict';
const getLang=()=>localStorage.getItem('droop-lang')||((navigator.language||'en').toLowerCase().startsWith('es')?'es':'en');
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], txt=(s,v,r=document)=>{const e=typeof s==='string'?$(s,r):s;if(e&&v!=null)e.textContent=v;};
const common={en:{all:'All tools',image:'Image',video:'Video',audio:'Audio',privacy:'Local processing · No uploads',runs:'✦ Runs locally',no:'No uploads',footer:'droop · Everything you need before you post.',footer2:'Private browser-based tools.',related:'Keep working',processing:'Processing',local:'Local',ready:'Ready',download:'Download'},es:{all:'Todas las herramientas',image:'Imagen',video:'Video',audio:'Audio',privacy:'Procesamiento local · Sin subidas',runs:'✦ Funciona localmente',no:'Sin subidas',footer:'droop · Todo lo que necesitás antes de publicar.',footer2:'Herramientas privadas desde tu navegador.',related:'Seguí trabajando',processing:'Procesamiento',local:'Local',ready:'Listo',download:'Descargar'}};
const pages={
'make-it-fit':{title:'Make It Fit — droop',es:{lead:'Subí una imagen, elegí dónde la querés usar y obtené automáticamente el recorte y las dimensiones correctas.',kicker:'IMAGEN · POPULAR',chips:['✦ Funciona localmente','Sin subidas','Lista para publicar'],drop:['Soltá una imagen acá','o hacé clic para elegir un archivo'],button:'Ajustar mi imagen',result:['Lista para','Resultado'],download:'Descargar imagen',info:[['Elegí el destino','No hace falta recordar dimensiones ni relaciones de aspecto.'],['Recorte automático','La imagen se centra y se adapta al formato seleccionado.'],['Procesamiento privado','Tu imagen permanece en tu dispositivo mientras se prepara.']]}},
'under-x-mb':{title:'Under X MB — droop',es:{lead:'Definí el tamaño máximo y dejá que droop encuentre la mejor calidad de imagen posible sin superar ese límite.',kicker:'IMAGEN · INTELIGENTE',chips:['✦ Funciona localmente','Calidad automática','Sin subidas'],drop:['Soltá una imagen acá','procesada en tu dispositivo'],button:'Comprimir al límite',result:['Original','Resultado','Calidad JPEG','Dimensiones'],download:'Descargar imagen comprimida',info:[['Elegí el límite','Ingresá el máximo de KB o MB que necesitás cumplir.'],['La calidad es automática','La herramienta busca el mejor resultado para que no tengas que adivinar.'],['Redimensiona solo si hace falta','Si comprimir no alcanza, las dimensiones se reducen progresivamente.']]}},
'release-pack':{title:'Release Pack — droop',es:{lead:'Subí una sola pieza gráfica y exportá un set completo de tamaños listos para una publicación, lanzamiento, perfil o redes.',kicker:'IMAGEN · FLUJO',chips:['✦ Funciona localmente','Descarga ZIP','Varios tamaños'],drop:['Soltá tu diseño acá','una imagen se convierte en un pack completo'],button:'Generar pack',packReady:'PACK LISTO',download:'Descargar ZIP',options:['Lanzamiento musical','Lanzamiento en YouTube','Pack para redes','Pack de perfil'],info:[['Una sola subida','Partí de una portada, logo o diseño sin repetir la misma tarea.'],['Packs preparados','Elegí un flujo y droop prepara los tamaños más comunes.'],['Descargá todo junto','Bajá todos los archivos generados en un solo ZIP cuando estén listos.']]}},
'metadata-cleaner':{title:'Metadata Cleaner — droop',es:{lead:'Creá una copia nueva de una imagen sin los metadatos comunes de cámara, fecha, hora o ubicación del archivo original.',kicker:'IMAGEN · PRIVACIDAD',chips:['✦ Funciona localmente','Sin subidas','Mantiene dimensiones'],drop:['Soltá una foto o imagen acá','creá una copia limpia'],button:'Eliminar metadatos',result:['Original','Limpia','Dimensiones','Formato'],download:'Descargar imagen limpia',info:[['Archivo de imagen nuevo','Los píxeles visibles se vuelven a exportar en un archivo nuevo.'],['Mantiene el formato','Las entradas PNG, WebP y JPEG conservan un formato de salida apropiado.'],['Flujo local','El proceso de limpieza ocurre en tu dispositivo.']]}},
'image-converter':{title:'Image Converter — droop',es:{lead:'Convertí imágenes entre JPG, PNG y WebP sin subirlas a ningún lado. Conservá las dimensiones originales y controlá la calidad cuando haga falta.',kicker:'IMAGEN · ESTABLE',chips:['✦ Funciona localmente','Sin subidas','JPG · PNG · WebP'],drop:['Soltá una imagen para convertir','o hacé clic para elegir un archivo'],labels:['Convertir a','Calidad'],button:'Convertir imagen',result:['Original','Convertida','Tamaño original','Tamaño nuevo','Dimensiones'],download:'Descargar imagen convertida',info:[['Privado por defecto','Tu imagen permanece en este dispositivo mientras se convierte.'],['Conservá tus dimensiones','El conversor cambia el formato sin redimensionar la imagen.'],['Control de calidad simple','Elegí el equilibrio entre tamaño y calidad para JPG y WebP.']],related:[['Under X MB','Comprimí una imagen a un tamaño máximo.'],['Make It Fit','Redimensioná para YouTube, Instagram, Spotify y más.'],['Metadata Cleaner','Creá una copia limpia de tu imagen.']]}},
'video-under-x-mb':{title:'Video Under X MB — droop',es:{lead:'Elegí el tamaño máximo que necesitás y comprimí el video hacia ese objetivo sin subirlo.',kicker:'VIDEO · BETA',chips:['✦ Funciona localmente','Tamaño objetivo','Salida MP4'],drop:['Soltá un video acá','el procesamiento queda en este dispositivo'],labels:['Tamaño máximo de salida','Calidad de audio'],button:'Calcular compresión',options:['Pequeña','Pequeña equilibrada','Recomendada','Alta'],result:['Duración','Original','Objetivo','Estado'],info:[['Definí el tamaño que necesitás','Útil para límites de subida en redes sociales, chats y sitios web.'],['Dos modos de compresión','Elegí entre procesamiento más rápido o uno más lento enfocado en calidad.'],['Mantené la pestaña abierta','El procesamiento puede tardar con videos largos o pesados.']]}},
'video-trimmer':{title:'Video Trimmer — droop',es:{lead:'Elegí la sección exacta que querés conservar, previsualizala y exportá el clip directamente desde tu navegador.',kicker:'VIDEO · NUEVO',chips:['✦ Funciona localmente','Corte rápido','Corte preciso'],drop:['Soltá un video acá','o hacé clic para elegir un archivo'],times:['Inicio','Fin'],markers:['Usar posición actual como inicio','Usar posición actual como fin'],labels:['Modo de corte'],options:['Corte rápido · más veloz','Corte preciso · tiempo exacto'],button:'Cortar clip seleccionado',result:['Duración del clip','Tamaño de salida','Modo','Procesamiento'],download:'Descargar video recortado',info:[['Rápido cuando lo necesitás','El corte rápido evita una recodificación completa cuando el archivo lo permite.'],['Preciso cuando importa el tiempo','El corte preciso vuelve a exportar la sección seleccionada para ajustar mejor los tiempos.'],['Tu archivo se queda con vos','Todo el flujo corre en tu navegador y en tu dispositivo.']],related:[['Video Under X MB','Comprimí el clip terminado a un límite de tamaño.'],['Extract Audio','Convertí tu video a MP3 o WAV.'],['Social Safe Zones','Revisá contenido vertical antes de publicar.']]}},
'extract-audio':{title:'Extract Audio — droop',es:{lead:'Convertí un video en MP3 o WAV para ediciones, música, samples, voz o podcasts, sin subirlo.',kicker:'AUDIO · ESTABLE',chips:['✦ Funciona localmente','MP3 hasta 320 kbps','WAV'],drop:['Soltá un video acá','o hacé clic para elegir un archivo'],labels:['Formato de salida'],options:['MP3 · más chico y compatible','WAV · sin compresión','128 kbps · pequeño','192 kbps · recomendado','256 kbps · alto','320 kbps · máximo'],button:'Extraer audio',result:['Duración','Formato','Tamaño de salida','Procesamiento'],download:'Descargar audio',info:[['Hecho para reutilizar rápido','Sacá el audio de un video y reutilizalo en una edición, sample o trabajo de voz.'],['Elegí compacto o sin comprimir','Usá MP3 por compatibilidad y tamaño, o WAV para una exportación sin compresión.'],['Sin paso de subida','Tu video original permanece en este dispositivo mientras se prepara el audio.']],related:[['Video Trimmer','Cortá la sección exacta antes de extraer el audio.'],['Audio Converter','Convertí otro archivo de audio a MP3 o WAV.'],['Audio Trimmer','Recortá el audio extraído a la parte que necesitás.']]}},
'audio-converter':{title:'Audio Converter — droop',es:{lead:'Convertí archivos de audio comunes a MP3 o WAV sin subirlos. Elegí formato y calidad, y descargá el resultado.',kicker:'AUDIO · ESTABLE',chips:['✦ Funciona localmente','MP3 · WAV','Sin subidas'],drop:['Soltá un archivo de audio acá','MP3, WAV, M4A, AAC, OGG, FLAC, Opus y más'],labels:['Convertir a'],options:['128 kbps · pequeño','192 kbps · recomendado','256 kbps · alto','320 kbps · máximo'],button:'Convertir audio',result:['Desde','A','Tamaño de salida','Duración'],download:'Descargar audio convertido',info:[['Formatos de audio comunes','Usá el archivo que ya tenés y exportalo a un formato de destino más simple.'],['Elegí la calidad MP3','Equilibrá tamaño y calidad con el selector de bitrate.'],['Flujo privado','El procesamiento ocurre en el navegador en vez de subir tu audio.']]}},
'audio-trimmer':{title:'Audio Trimmer — droop',es:{lead:'Elegí la sección exacta de una canción, sample, nota de voz o podcast que querés conservar y exportá solo esa parte.',kicker:'AUDIO · NUEVO',chips:['✦ Funciona localmente','MP3 · WAV','Sin subidas'],drop:['Soltá audio para recortar','canciones, samples, notas de voz y más'],times:['INICIO · segundos','FIN · segundos'],markers:['Usar posición actual como inicio','Usar posición actual como fin'],labels:['Exportar como'],button:'Recortar audio',result:['Duración del clip','Tamaño de salida','Procesamiento','Listo'],download:'Descargar clip de audio',info:[['Previsualizá primero','Escuchá la fuente y ubicá el corte alrededor de la parte que querés.'],['Ajuste fino','Modificá inicio y fin con los controles o campos numéricos.'],['Exportá el clip','Guardá la sección seleccionada como MP3 o WAV.']]}},
'safe-zones':{title:'Social Safe Zones — droop',es:{lead:'Previsualizá las zonas aproximadas que puede cubrir la interfaz antes de publicar contenido vertical en TikTok, Instagram Reels o YouTube Shorts.',kicker:'SOCIAL · VISTA PREVIA',chips:['✦ Funciona localmente','TikTok · Reels · Shorts','Solo vista previa'],drop:['Soltá una imagen vertical acá','previsualizá dónde la interfaz puede tapar contenido'],info:[['Detectá las zonas de riesgo','Usá la superposición como guía conservadora para mantener visible el contenido importante.'],['Cambiá de plataforma','Compará TikTok, Reels y Shorts sin volver a cargar la imagen.'],['Tu original queda intacto','Esta herramienta solo muestra una vista previa; no modifica la imagen.']]}}
};
function key(){const p=location.pathname;if(p.includes('/extract-audio/'))return'extract-audio';const n=p.split('/').pop()||'';return n.replace(/\.html$/,'')||'index';}
function setOptions(sel,arr){const o=$$(sel);arr.forEach((v,i)=>txt(o[i],v));}
function setInfo(p){$$('.tool-info .info-card').forEach((card,i)=>{if(!p.info?.[i])return;txt($('h3',card),p.info[i][0]);txt($('p',card),p.info[i][1]);});}
function setRelated(p,c){txt('.related h2',c.related);$$('.related-grid a').forEach((a,i)=>{if(!p.related?.[i])return;const span=$('span',a);const nodes=[...a.childNodes].filter(n=>n.nodeType===3);if(nodes[0])nodes[0].nodeValue=p.related[i][0];txt(span,p.related[i][1]);});}
function applyPage(k,p,l,c){document.title=p.title||document.title;txt('.tool-lead',p.lead);txt('.tool-kicker',p.kicker);const chips=$$('.trust-chip');p.chips?.forEach((v,i)=>txt(chips[i],v));
const drop=$('.drop-zone');if(drop&&p.drop){txt($('strong',drop),p.drop[0]);txt($('span',drop),p.drop[1]);}
if(k==='make-it-fit'){txt('#processButton',p.button);setOptions('.result-meta span',p.result);txt('#downloadButton',p.download);}
if(k==='under-x-mb'){txt('#compressButton',p.button);setOptions('#compressResult .comparison-grid span',p.result);txt('#compressDownloadButton',p.download);}
if(k==='release-pack'){txt('#packGenerateButton',p.button);txt('.pack-result-head span',p.packReady);txt('#packDownloadAll',p.download);setOptions('#packSelect option',p.options);}
if(k==='metadata-cleaner'){txt('#metadataCleanButton',p.button);setOptions('#metadataResult .comparison-grid span',p.result);txt('#metadataDownloadButton',p.download);}
if(k==='image-converter'){const labels=$$('.controls label');p.labels?.forEach((v,i)=>{if(i===1){const st=$('#converterQualityValue');if(labels[i])labels[i].childNodes[0].nodeValue=v+' · ';if(st&&st.parentElement!==labels[i]){} }else txt(labels[i],v)});txt('#converterButton',p.button);setOptions('#converterResult .comparison-grid span',p.result.slice(0,4));txt('#converterResult .result-meta span',p.result[4]);txt('#converterDownload',p.download);setRelated(p,c);}
if(k==='video-under-x-mb'){setOptions('.controls>label',p.labels);setOptions('#videoAudioBitrate option',p.options);txt('#videoAnalyzeButton',p.button);setOptions('#videoAnalyzeResult .comparison-grid span',p.result);}
if(k==='video-trimmer'){setOptions('.trim-time-grid label',p.times);setOptions('.trim-marker-buttons button',p.markers);txt('.controls label',p.labels[0]);setOptions('#trimMode option',p.options);txt('#trimButton',p.button);setOptions('#trimResult .comparison-grid span',p.result);txt('#trimResult .comparison-grid div:nth-child(4) strong',c.local);txt('#trimDownload',p.download);setRelated(p,c);}
if(k==='extract-audio'){txt('.controls label',p.labels[0]);setOptions('#audioExtractFormat option',p.options.slice(0,2));setOptions('#audioExtractQuality option',p.options.slice(2));txt('#audioExtractButton',p.button);setOptions('#audioExtractResult .comparison-grid span',p.result);txt('#audioExtractResult .comparison-grid div:nth-child(4) strong',c.local);txt('#audioExtractDownload',p.download);setRelated(p,c);}
if(k==='audio-converter'){txt('.controls label',p.labels[0]);setOptions('#audioConvertQuality option',p.options);txt('#audioConvertButton',p.button);setOptions('#audioConvertResult .comparison-grid span',p.result);txt('#audioConvertDownload',p.download);}
if(k==='audio-trimmer'){setOptions('.trim-time-grid label',p.times);setOptions('.trim-marker-buttons button',p.markers);txt('.controls label',p.labels[0]);txt('#audioTrimButton',p.button);setOptions('#audioTrimResult .comparison-grid span',p.result);txt('#audioTrimResult .comparison-grid div:nth-child(3) strong',c.local);txt('#audioTrimResult .comparison-grid div:nth-child(4) strong',c.download);txt('#audioTrimDownload',p.download);}
setInfo(p);}
function apply(){const l=getLang(),c=common[l],k=key(),p=pages[k]?.[l];document.documentElement.lang=l;const nav=$$('.top-nav a');[c.all,c.image,c.video,c.audio].forEach((v,i)=>txt(nav[i],v));txt('.privacy-pill',c.privacy);txt('.tool-breadcrumb a',c.all);const foot=$$('footer span');txt(foot[0],c.footer);txt(foot[1],c.footer2);let sw=$('.lang-switch');if(!sw){sw=document.createElement('button');sw.className='lang-switch';sw.type='button';$('.site-header')?.appendChild(sw);}txt(sw,l==='es'?'EN':'ES');sw.onclick=()=>{localStorage.setItem('droop-lang',l==='es'?'en':'es');location.reload();};if(p)applyPage(k,p,l,c);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',apply);else apply();
})();